import mongoose from "mongoose";

const fixandFlipSchema = new mongoose.Schema(
  {
    additionalPropertyInfo: String,
    addressCity: String,
    addressState: String,
    addressZip: String,
    afterRepairValue: String,
    armsLengthDescription: String,
    authorizedSign: String,
    authorizedSignatory: String,
    bestTerms: String,
    birthDate: String,
    birthMonth: String,
    birthYear: String,
    borrowerCell: String,
    borrowerCitizenship: String,
    borrowerEmail: String,
    borrowerLast: String,
    borrowerSocialSecurity: String,
    borrowingEntityInformation: String,
    borrowingEntityOwned: Number,
    brokerPoints: String,
    closingDate: String,
    constructionBudgetPercentage: Number,
    constructionHoldback: String,
    contactLastName: String,
    creditScore: String,
    dateofIncorp: String,
    entityAddress: String,
    entityName: String,
    entityType: String,
    exitStrategry: String,
    firstName: String,
    guranteeLoan: String,
    homeAddress: String,
    initialLoanAmount: String,
    insuranceCompany: String,
    interestRate: String,
    interestTerm: Number,
    intrestMethod: String,
    isCondominium: String,
    percentageOrAmount: String,
    percentageOrAmount2: String,
    personallyGuranteeing: Number,
    points: String,
    preferredClosingAttorney: String,
    propertyPurchasePrice: String,
    propertySource: String,
    propertyType: String,
    purchaseAmount: Number,
    refinance: String,
    renovationBudget: String,
    socialSecurity: String,
    termMonths: String,
    titleCompany: String,
    transactionArmslength: String,
    wholesalerPay: String,
    wholesalerSource: String,
    // New fields added
    userEmail: String,
    additonalPropertyInfo: String,
    buyerSellerDescribe: String,
    experiencedwithBorrowing: String,
    experienceWithRealEstate: String,
    purchase: String,
    renovationDescript: String,
  },
  {
    timestamps: true,
  }
);

const FixForm = mongoose.model("FixForm", fixandFlipSchema);
export default FixForm;
