import mongoose from "mongoose";

const fixandFlipSchema = new mongoose.Schema(
  {
    additionalPropertyInfo: { type: String },
    addressCity: { type: String },
    addressState: { type: String },
    addressZip: { type: String },
    afterRepairValue: { type: String },
    armsLengthDescription: { type: String },
    authorizedSignatory: { type: String },
    bestTerms: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    borrowerEmail: { type: String },
    borrowerLast: { type: String },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    closingDate: { type: String },
    contactLastName: { type: String },
    dateofIncorp: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    experienceWithRealEstate: { type: Number },
    exitStrategy: { type: String },
    ficoScore: { type: String },
    firstName: { type: String },
    homeAddress: { type: String },
    insuranceCompany: { type: String },
    isCondominium: { type: String },
    personallyGuranteeing: { type: Number },
    preferredClosingAttorney: { type: String },
    propertyMonthlyInsurance: { type: String },
    propertyMonthlyPropertyTaxes: { type: String },
    propertyMonthlyUtilityBills: { type: String },
    propertyOtherMonthlyExpenses: { type: String },
    propertyPurchasePrice: { type: String },
    propertyRehabCost: { type: String },
    propertySource: { type: String },
    propertyType: { type: String },
    purchaseorRefinance: { type: String },
    renovationDescript: { type: [String] },
    socialSecurity: { type: String },
    titleCompany: { type: String },
    userEmail: { type: String },
  },
  {
    timestamps: true,
  }
);

const FixForm = mongoose.model("FixForm", fixandFlipSchema);
export default FixForm;
