import mongoose from "mongoose";

const groundUpSchema = new mongoose.Schema(
  {
    additonalPropertyInfo: { type: String },
    addressCity: { type: String },
    addressState: { type: String },
    addressZip: { type: String },
    afterRepairValue: { type: String },
    armsLengthDescription: { type: String },
    asIsValue: { type: String },
    authorizedSignatory: { type: String },
    bestTerms: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    borrowerEmail: { type: String },
    borrowerLast: { type: String },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    closingDate: { type: String },
    contactLastName: { type: String },
    dateofIncorp: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    experienceWithRealEstate: { type: Number },
    exitStrategy: { type: String },
    firstName: { type: String },
    grossMonthlyRent: { type: String },
    homeAddress: { type: String },
    insuranceCompany: { type: String },
    isCondominium: { type: String },
    marketValueAfterCompletion: { type: String },
    ownedByBorrower: { type: String },
    ownerOfRecord: { type: String },
    personallyGuranteeing: { type: Number },
    permitsInPlace: { type: String },
    preferredClosingAttorney: { type: String },
    propertyMonthlyHOAFee: { type: String },
    propertyMonthlyInsurance: { type: String },
    propertyMonthlyOtherExpenses: { type: String },
    propertyMonthlyTaxes: { type: String },
    propertyPurchasePrice: { type: String },
    propertySource: { type: String },
    propertyType: { type: String },
    proposedConstructionBudget: { type: String },
    purchaseorRefinance: { type: String },
    renovationDescript: { type: [String] }, // Array of strings
    sellerCredit: { type: String },
    socialSecurity: { type: String },
    subdividedIntoLots: { type: String },
    titleCompany: { type: String },
    userEmail: { type: String },
    ficoScore: { type: String },
    uploadedDocuments: { type: [String] },
  },
  {
    timestamps: true,
  }
);

const GroundUp = mongoose.model("GroundUp", groundUpSchema);
export default GroundUp;
