import mongoose from "mongoose";

const multiFamilySchema = new mongoose.Schema(
  {
    userEmail: { type: String },
    addressCity: { type: String },
    addressState: { type: String },
    addressZip: { type: String },
    afterRepairValue: { type: String },
    annualAdministrativeManagementFees: { type: String },
    annualHOADues: { type: String },
    annualInsurance: { type: String },
    annualMarketingExpense: { type: String },
    annualPayrollExpense: { type: String },
    annualPropertyManagementFees: { type: String },
    annualRepairsMaintenanceExpenses: { type: String },
    annualReplacementReserve: { type: String },
    annualTaxes: { type: String },
    annualUtilitiesExpenses: { type: String },
    asIsValue: { type: String },
    authorizedSign: { type: String },
    background: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCitizenshipStatus: { type: String },
    borrowerEmail: { type: String },
    borrowingCreditScore: { type: Number },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    brokerPoints: { type: String },
    capitalPoints: { type: String },
    capitalPointsExit: { type: String },
    cashOut: { type: String },
    closingDate: { type: String },
    collectCredit: { type: String },
    completedCapex: { type: String },
    constructionBudgetPercentage: { type: Number },
    constructionHoldback: { type: String },
    contactLastName: { type: String },
    creditScore: { type: String },
    dateofIncorp: { type: String },
    debt: { type: String },
    debtValue: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    exitFees: { type: String },
    exitStrat: { type: String },
    firstName: { type: String },
    grossMonthlyRent: { type: String },
    guranteeLoan: { type: String },
    homeAddress: { type: String },
    initialLoanAmount: { type: String },
    insuranceCompany: { type: String },
    interestRate: { type: String },
    interestTerm: { type: Number },
    intrestMethod: { type: String },
    investedCapital: { type: String },
    lastName: { type: String },
    liquidity: { type: String },
    percentageOrAmount: { type: String },
    percentageOrAmount2: { type: String },
    personallyGuranteeing: { type: Number },
    phoneNumber: { type: String },
    points: { type: String },
    preferredClosingAttorney: { type: String },
    propertyType: { type: String },
    purchase: { type: String },
    purchaseAmount: { type: Number },
    purchaseDate: { type: String },
    propertyPurchasePrice: { type: String },
    purchaseorRefinance: { type: String },
    redFlags: { type: String },
    socialSecurity: { type: String },
    termMonths: { type: String },
    titleCompany: { type: String },
  },
  {
    timestamps: true,
  }
);

const MultiFam = mongoose.model("MultiFam", multiFamilySchema);
export default MultiFam;
