import mongoose from "mongoose";

const multiFamilySchema = new mongoose.Schema(
  {
    addressCity: { type: String },
    addressState: { type: String },
    addressZip: { type: String },
    afterRepairValue: { type: String },
    annualAdministrativeManagementFees: { type: String },
    annualHOADues: { type: String },
    annualInsurance: { type: String },
    annualMarketingExpense: { type: String },
    annualPayrollExpense: { type: String },
    annualPropertyManagementFees: { type: String },
    annualRepairsMaintenanceExpenses: { type: String },
    annualReplacementReserve: { type: String },
    annualTaxes: { type: String },
    annualUtilitiesExpenses: { type: String },
    asIsValue: { type: String },
    authorizedSignatory: { type: String },
    background: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCitizenshipStatus: { type: String },
    borrowerEmail: { type: String },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    cashOut: { type: String },
    closingDate: { type: String },
    completedCapex: { type: String },
    contactLastName: { type: String },
    dateofIncorp: { type: String },
    debt: { type: String },
    debtValue: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    exitStrat: { type: String },
    ficoScore: { type: String },
    firstName: { type: String },
    grossMonthlyRent: { type: String },
    homeAddress: { type: String },
    insuranceCompany: { type: String },
    investedCapital: { type: String },
    isCondominium: { type: String },
    lastName: { type: String },
    liquidity: { type: String },
    personallyGuranteeing: { type: Number },
    phoneNumber: { type: String },
    preferredClosingAttorney: { type: String },
    propertyMonthlyInsurance: { type: String },
    propertyMonthlyPropertyTaxes: { type: String },
    propertyMonthlyUtilityBills: { type: String },
    propertyOtherMonthlyExpenses: { type: String },
    propertyPurchasePrice: { type: String },
    propertyRehabCost: { type: String },
    propertySource: { type: String },
    propertyType: { type: String },
    purchaseDate: { type: String },
    purchaseorRefinance: { type: String },
    redFlags: { type: String },
    renovationDescript: { type: [String] }, // Array of strings
    socialSecurity: { type: String },
    titleCompany: { type: String },
    uploadedDocuments: { type: [String] },
    userEmail: { type: String },
    referralInfo: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

const MultiFam = mongoose.model("MultiFam", multiFamilySchema);
export default MultiFam;
