import mongoose from "mongoose";

const ownershipSchema = new mongoose.Schema({
  ownersName: { type: String },
  title: { type: String },
  estimateasvalue: { type: String },
  address: { type: String },
  programType: { type: String },
  tin: { type: String },
});

const notesPayableSchema = new mongoose.Schema({
  ownersName: { type: String },
  balance: { type: String },
  currentBalance: { type: String },
  paymentAmount: { type: String },
  frequencey: { type: String },
  howSecured: { type: String },
});

const stocksAndBondsSchema = new mongoose.Schema({
  numbShares: { type: String },
  numbofSecurities: { type: String },
  cost: { type: String },
  marketValue: { type: String },
  dateofQuoatation: { type: String },
  totalValue: { type: String },
});

const realEstateSchema = new mongoose.Schema({
  realEstateType: { type: String },
  address: { type: String },
  costPersonal: { type: String },
  purchaseDate: { type: String },
  originalCost: { type: String },
  presentMarketValue: { type: String },
  nameAddress: { type: String },
  AmountPayment: { type: String },
  statusMortgage: { type: String },
});

const project99Schema = new mongoose.Schema(
  {
    accountsPayable: { type: String },
    anualAdministrativeManagementFees: { type: String },
    annualHOADues: { type: String },
    annualInsurance: { type: String },
    annualMarketingExpense: { type: String },
    annualPayrollExpense: { type: String },
    annualPropertyManagementFees: { type: String },
    annualRepairsMaintenanceExpenses: { type: String },
    annualReplacementReserve: { type: String },
    annualTaxes: { type: String },
    annualUtilitiesExpenses: { type: String },
    aplicantA: { type: String },
    armsLengthDescription: { type: String },
    authorizedSignatory: { type: String },
    automobiles: { type: String },
    background: { type: String },
    bankruptcyProtection: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    borrowerEmail: { type: String },
    borrowerLast: { type: String },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    businessDefault: { type: String },
    businessEmail: { type: String },
    businessPercentage: { type: String },
    businessTaxID: { type: String },
    cashOnHand: { type: String },
    closingDate: { type: String },
    coMaker: { type: String },
    completedCapex: { type: String },
    daysDelenquet: { type: String },
    debt: { type: String },
    debtValue: { type: String },
    dBATradename: { type: String },
    ethinicity: { type: String },
    experienceWithRealEstate: { type: Number },
    financingDelinquent: { type: String },
    firstName: { type: String },
    gender: { type: String },
    industryExperience: { type: String },
    insuranceCompany: { type: String },
    investedCapital: { type: String },
    isArrested: { type: String },
    isCriminalOffense: { type: String },
    isIndictment: { type: String },
    lastName: { type: String },
    legalAction: { type: String },
    legalClaims: { type: String },
    lifeInsurance: { type: String },
    lifeInsuranceHeld: { type: String },
    loanGuarantor: { type: String },
    loanPurpose: { type: String },
    managmentCompany: { type: String },
    moneyperYear: { type: String },
    mortgagesRealEstate: { type: String },
    motivation: { type: String },
    netInvestmentIncome: { type: String },
    netInvestmentIncomeLiab: { type: String },
    notesReceivable: { type: String },
    operatingBusinessLegalName: { type: String },
    otherAssets: { type: String },
    otherIncome: { type: String },
    otherLiabilities: { type: String },
    otherPersonalProperty: { type: String },
    otherSpecialDebt: { type: String },
    ownershipOfApplicant: { type: [ownershipSchema] },
    personallyGuranteeing: { type: Number },
    plantoUse: { type: String },
    positionsHeld: { type: [String] },
    primaryBusinessAddress: { type: String },
    primaryBusinessAddressCounty: { type: String },
    primaryBusinessAddressState: { type: String },
    primaryBusinessAddressZip: { type: String },
    primaryBusinessPhone: { type: String },
    preferredClosingAttorney: { type: String },
    projectAddress: { type: String },
    projectAddressCounty: { type: String },
    projectAddressState: { type: String },
    projectAddressZip: { type: String },
    provisionFederalIncomeTax: { type: String },
    realEstate: { type: [realEstateSchema] },
    realEstateAssets: { type: String },
    realEstateIncomeSource: { type: String },
    renovationDescript: { type: [String] },
    runningCompany: { type: String },
    salary: { type: String },
    savingsAccounts: { type: String },
    smallBusiness: { type: String },
    socialSecurity: { type: String },
    stateBusiness: { type: String },
    stocksAndBonds: { type: [stocksAndBondsSchema] },
    stocksBonds: { type: String },
    suspendedFederal: { type: String },
    titleCompany: { type: String },
    uSCISRegNum: { type: String },
    unpaidTaxes: { type: String },
    userEmail: { type: String },
    veteran: { type: String },
    whichApply: { type: [String] },
    whichImportant: { type: String },
  },
  {
    timestamps: true,
  }
);

const Project99 = mongoose.model("Project99", project99Schema);
export default Project99;
