import mongoose from "mongoose";

const project99Schema = new mongoose.Schema(
  {
    userEmail: String,
    firstName: String,
    lastName: String,
    PrimaryBusinessAddressCity: String,
    marriageStatus: String,
    AmountPayment: String,
    Businesspresentlysuspended: String,
    Fnancingdelinquent: String,
    PrimaryBusinessAddress: String,
    PrimaryBusinessAddressCounty: String,
    PrimaryBusinessAddressState: String,
    PrimaryBusinessAddressZip: String,
    PrimaryBusinessPhone: String,
    ProjectAddress: String,
    ProjectAddressCounty: String,
    ProjectAddressState: String,
    ProjectAddressZip: String,
    SeperatefederalGovernmentEmployee: String,
    address: String,
    accountsPayable: String,
    affiliatesBankruptcy: String,
    affiliatesInformation: Array,
    affiliatesLegalAction: String,
    aplicantA: String,
    automobiles: String,
    bankruptcyProtection: String,
    birthDate: String,
    birthMonth: String,
    birthYear: String,
    businessCoOwner: String,
    businessDefault: String,
    businessEmail: String,
    businessHaveAffiliates: String,
    businessPercentage: String,
    businessProducts: String,
    businessTaxID: String,
    cashonHand: String,
    citizenshipStatus: String,
    coMaker: String,
    countryofCitizenship: String,
    creditScore: String,
    dBATradename: String,
    daysDelenquet: String,
    ethinicity: String,
    federalGovLoss: String,
    federalGovernmentEmployee: String,
    financeAgreeement: String,
    financingDelinquent: String,
    gender: String,
    industryExperience: String,
    installmentAccount: String,
    isArrested: String,
    isCriminalOffense: String,
    isIndictment: String,
    legalAction: String,
    legalActionDetails: String,
    legalClaims: String,
    lifeInsurance: String,
    lifeInsuranceHeld: String,
    loanDetails: String,
    loanGuarantor: String,
    loanInsurance: String,
    managmentCompany: String,
    moneyperYear: String,
    monthlySalesExpected: String,
    mortgagesRealEstate: String,
    motivation: String,
    netInvestmentIncome: String,
    netInvestmentIncomeLiab: String,
    notesPayable: Array,
    notesReceivable: String,
    numbEmployees: String,
    operatingBusinessLegalName: String,
    otherAssets: String,
    otherIncome: String,
    otherLiabilities: String,
    otherPersonalProperty: String,
    otherSpecialDebt: String,
    plantoUse: String,
    positionsHeld: String,
    provisionFederalIncomeTax: String,
    race: String,
    realEstate: Array,
    realEstateIncomeSource: String,
    retirementAccount: String,
    revenuesDerived: String,
    runningCompany: String,
    salary: String,
    savingsAccounts: String,
    score: String,
    smallBusiness: String,
    socialSecurity: String,
    stateBusiness: String,
    stocksAndBonds: Array,
    stocksBonds: String,
    suspendedFederal: String,
    tenPercentageFederal: String,
    tenPercentageGS13: String,
    totalLiabilities: String,
    unpaidTaxes: String,
    veteran: String,
    whichImportant: String,
  },
  {
    timestamps: true,
  }
);

const Project99 = mongoose.model("Project99", project99Schema);
export default Project99;
