import mongoose from "mongoose";

const rentalModelSchema = new mongoose.Schema(
  {
    amortizationType: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    borrowerEmail: { type: String },
    borrowerLast: { type: String },
    borrowerSocialSecurity: { type: String },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    brokerPoints: { type: String },
    cashFlowmaxAsValue: { type: String },
    cashFlowminAsValue: { type: String },
    cashFlowpropertyMan: { type: String },
    closingDate: { type: String },
    contactLastName: { type: String },
    creditScore: { type: String },
    dateofIncorp: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    estimatedValue: { type: Number },
    experienceWithRealEstate: { type: String },
    firstName: { type: String },
    grossmontly: { type: String },
    insuranceCompany: { type: String },
    interestRate: { type: String },
    interestTerm: { type: Number },
    intrestMethod: { type: String },
    loanPurpose: { type: String },
    loanRecourse: { type: String },
    loanToValue: { type: String },
    ltv: { type: String },
    maxAsValue: { type: String },
    minAsValue: { type: String },
    numProperties: { type: Number },
    oneTimeYield: { type: Number },
    percentageOrAmount: { type: String },
    percentageOrAmount2: { type: String },
    personallyGuranteeing: { type: Number },
    points: { type: String },
    prePayPen: { type: String },
    preferredClosingAttorney: { type: String },
    programType: { type: String },
    propertyMan: { type: String },
    propertyType: { type: String },
    purchasePriceProperty: { type: String },
    rateBuyDown: { type: Number },
    rateType: { type: String },
    socialSecurity: { type: String },
    state: { type: String },
    termMonths: { type: String },
    titleCompany: { type: String },
    portfolioProperties: { type: Array },
    userEmail: { type: String },
  },
  {
    timestamps: true,
  }
);

const Rental = mongoose.model("Rental", rentalModelSchema);
export default Rental;
