import mongoose from "mongoose";

const sbaModelSchema = new mongoose.Schema(
  {
    userEmail: String,
    accountsPayable: String,
    automobiles: String,
    bankruptcyProtection: String,
    birthDate: String,
    birthMonth: String,
    birthYear: String,
    businessDefault: String,
    cashonHand: String,
    citizenshipStatus: String,
    closingDate: String,
    coMaker: String,
    countryofCitizenship: String,
    creditScore: String,
    daysDelenquet: String,
    email: String,
    ethinicity: String,
    fileUploadUrl: Array,
    financingDelinquent: String,
    gender: String,
    installmentAccount: String,
    insuranceCompany: String,
    isArrested: String,
    isCriminalOffense: String,
    isIndictment: String,
    legalAction: String,
    legalClaims: String,
    lifeInsurance: String,
    lifeInsuranceHeld: String,
    loanGuarantor: String,
    loanInsurance: String,
    mortgagesRealEstate: String,
    netInvestmentIncome: String,
    netInvestmentIncomeLiab: String,
    notesPayable: Array,
    notesReceivable: String,
    otherAssets: String,
    otherIncome: String,
    otherLiabilities: String,
    otherPersonalProperty: String,
    otherSpecialDebt: String,
    preferredClosingAttorney: String,
    provisionFederalIncomeTax: String,
    race: String,
    realEstate: Array,
    realEstateAssets: String,
    realEstateIncomeSource: String,
    retirementAccount: String,
    salary: String,
    savingsAccounts: String,
    smallBusiness: String,
    socialSecurity: String,
    stocksAndBonds: Array,
    stocksBonds: String,
    suspendedFederal: String,
    titleCompany: String,
    totalLiabilities: String,
    unpaidTaxes: String,
    uscisRegNum: String,
    veteran: String,
    bankruptDetail: String,
    legalActionDetails: String,
    loanDetails: String,
    ficoScore: String,
    uploadedDocuments: { type: [String] },
  },
  {
    timestamps: true,
  }
);

const SBA = mongoose.model("SBA", sbaModelSchema);
export default SBA;
