import mongoose from "mongoose";

const singlePropertySchema = new mongoose.Schema(
  {
    userEmail: { type: String },
    amortizationType: { type: String },
    annualExpenses: { type: String },
    annualInsurance: { type: String },
    annualNOI: { type: String },
    annualRepair: { type: String },
    annualTaxes: { type: String },
    annualUtilityExpenses: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowExperience: { type: Number },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    borrowerEmail: { type: String },
    borrowerLast: { type: String },
    borrowingEntityInformation: { type: String },
    brokerPoints: { type: String },
    closingDate: { type: String },
    contactLastName: { type: String },
    creditScore: { type: String },
    dateofIncorp: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    estimatedAsIsValue: { type: String },
    experienceWithRealEstate: { type: String },
    ficoScore: { type: Number },
    firstName: { type: String },
    grossMonthlyRent: { type: String },
    hoa: { type: String },
    insuranceCompany: { type: String },
    interestRate: { type: String },
    interestTerm: { type: Number },
    intrestMethod: { type: String },
    loanPurpose: { type: String },
    loanToValue: { type: Number },
    oneTimeYield: { type: Number },
    personallyGuranteeing: { type: Number },
    points: { type: String },
    prePayPen: { type: String },
    preferredClosingAttorney: { type: String },
    previosulyBankrupt: { type: String },
    programType: { type: String },
    propertyAddress: { type: String },
    propertyFees: { type: String },
    propertyType: { type: String },
    purchasePriceProperty: { type: String },
    rateBuyDown: { type: Number },
    rateType: { type: String },
    shortForSale: { type: String },
    socialSecurity: { type: String },
    targetLTV: { type: String },
    termMonths: { type: String },
    titleCompany: { type: String },
    totalAnnualIncome: { type: String },
  },
  {
    timestamps: true,
  }
);

const SingleProperty = mongoose.model("SingleProperty", singlePropertySchema);
export default SingleProperty;
