import mongoose from "mongoose";

const singlePropertySchema = new mongoose.Schema(
  {
    userEmail: { type: String },
    firstName: { type: String },
    borrowerLast: { type: String },
    borrowerEmail: { type: String },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    personallyGuranteeing: { type: Number },
    experienceWithRealEstate: { type: Number },
    bestTerms: { type: String },
    armsLengthDescription: { type: String },
    authorizedSignatory: { type: String },
    borrowingEntityInformation: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    dateofIncorp: { type: String },
    contactLastName: { type: String },
    entityAddress: { type: String },
    borrowingEntityOwned: { type: Number },
    propertyAddress: { type: String },
    addressCity: { type: String },
    addressZip: { type: String },
    addressState: { type: String },
    propertyType: { type: String },
    purchaseorRefinance: { type: String },
    propertySource: { type: String },
    isCondominium: { type: String },
    renovationDescript: { type: [String] }, // Array of strings
    exitStrat: { type: String },
    cashOut: { type: String },
    purchaseDate: { type: String },
    purchasePriceProperty: { type: String },
    investedCapital: { type: String },
    completedCapex: { type: String },
    asIsValue: { type: String },
    background: { type: String },
    redFlags: { type: String },
    loanPurpose: { type: String },
    grossMonthlyRent: { type: String },
    propertyMonthlyTaxes: { type: String },
    propertyMonthlyInsurance: { type: String },
    propertyMonthlyHOAFee: { type: String },
    propertyMonthlyOtherExpenses: { type: String },
    preferredClosingAttorney: { type: String },
    closingDate: { type: String },
    insuranceCompany: { type: String },
    titleCompany: { type: String },
    birthMonth: { type: String },
    birthDate: { type: String },
    birthYear: { type: String },
    socialSecurity: { type: String },
    ficoScore: { type: String },
    uploadedDocuments: { type: [String] },
  },
  {
    timestamps: true,
  }
);

const SingleProperty = mongoose.model("SingleProperty", singlePropertySchema);
export default SingleProperty;
