import mongoose from "mongoose";

const stabalizedBridgeSchema = new mongoose.Schema(
  {
    userEmail: { type: String },
    addressCity: { type: String },
    addressState: { type: String },
    addressZip: { type: String },
    authorizedSign: { type: String },
    birthDate: { type: String },
    birthMonth: { type: String },
    birthYear: { type: String },
    borrowerCell: { type: String },
    borrowerCitizenship: { type: String },
    borrowerEmail: { type: String },
    borrowerLast: { type: String },
    borrowerSocialSecurity: { type: String },
    borrowingEntityInformation: { type: String },
    borrowingEntityOwned: { type: Number },
    brokerPoints: { type: String },
    closingDate: { type: String },
    collectCredit: { type: String },
    completedCapex: { type: String },
    contactLastName: { type: String },
    creditScore: { type: String },
    dateofIncorp: { type: String },
    entityAddress: { type: String },
    entityName: { type: String },
    entityType: { type: String },
    experienceWithRealEstate: { type: String },
    ficoScore: { type: Number },
    firstName: { type: String },
    grossAnnual: { type: String },
    grossMonthlyRent: { type: String },
    grossTaxes: { type: String },
    guranteeLoan: { type: String },
    hoa: { type: String },
    homeAddress: { type: String },
    insuranceCompany: { type: String },
    interestRate: { type: String },
    interestTerm: { type: Number },
    intrestMethod: { type: String },
    loanAmount: { type: String },
    loanPurpose: { type: String },
    loantoValue: { type: Number },
    percentageOrAmount: { type: String },
    percentageOrAmount2: { type: String },
    personallyGuranteeing: { type: Number },
    points: { type: String },
    preferredClosingAttorney: { type: String },
    propertyType: { type: String },
    purchaseDate: { type: String },
    purchasePriceProperty: { type: String },
    socialSecurity: { type: String },
    termMonths: { type: String },
    titleCompany: { type: String },
  },
  {
    timestamps: true,
  }
);

const StableBridge = mongoose.model("StableBridge", stabalizedBridgeSchema);
export default StableBridge;
